### ISSUE TITLE
how to loot lots of corpses without clicking each one

### ISSUE THREAD

**Issue by Roy-Kid** [cannonpalms/FasterLooting#11]
I am a new one to learn how to write script.
I want to start with a simple request that, for example, I use a AOE cast to kill a lot of mobs. Then their corpses start sparkle then I want to pick all things up. What I want to do is trigger a command or click a button then my character can do this by moving and picking up.
Is this can be done by writing a script or lua?

**Comment by cannonpalms** [comment]
Separate from the question of whether or not this is possible is the fact that it is almost certainly against the game's rules. 

As for the question of feasibility, however, the answer is unfortunately no. To my knowledge there is no way to interact with a corpse to loot it without a hardware action from the player.
