### ISSUE TITLE
Frame still shows up

### ISSUE THREAD

**Issue by shkabo** [cannonpalms/FasterLooting#2]
Hey, I've tried your addon but the frame is still showing up. Idk what's the reason. I disabled all addons, tried several other looting options and still it pops up. In some cases it really loots faster but in other, it's damn slow (regular looting)
This is for wow classic

**Comment by cannonpalms** [comment]
Regardless of whether or not the frame still appears, you can simply walk away as soon as you click to loot a mob. The items will be looted as you run away. 

However, I appreciate the issue. I will add implementing hiding the loot frame by default to my to-do list.

Cannon

**Comment by cannonpalms** [comment]
Hiding of the loot frame implemented in release version 1.1.0.
