### ISSUE TITLE
Legality & Adding Pickpocket as a trigger

### ISSUE THREAD

**Issue by Mursanian** [cannonpalms/FasterLooting#3]
First of all, I got the question: "Why shouldn't I be concerned that his Addon might be considered a cheat?"
Second thing, if there are no valid reasons why I should be concerned, can you please add Pick Pocket as a trigger for the Script/Addon, so Pickpocket is quicker too.

**Comment by cannonpalms** [comment]
Legality: Yes, this addon, as with any other addon written using APIs provided by Blizzard for addon development, is completely legal. 

Pickpocketing: The addon is not specific about which sources of loot it handles. As such, pickpocketing is already supported. If you have a bug to report with pickpocketing specifically, please open a new issue.
