### ISSUE TITLE
[Bug] Disabled auto loot with modifier and show loot frame

### ISSUE THREAD

**Issue by shkabo** [cannonpalms/FasterLooting#6]
By default auto loot modifier is shift + right click (if auto loot is disabled). When it's enabled, shift + right click would do the opposite - show frame and not auto loot.
Frame should be shown when auto loot modifier is used in combination with right click for looting, and it shouldn't auto loot all the items.
e.g. you find a chest in a dungeon, you want to see what's inside, and maybe loot just one item

**Comment by cannonpalms** [comment]
@shkabo The behavior you describe is how FasterLooting functions already. If you believe you have found a bug, please reopen this issue and provide specifics: configuration needed for reproduction, expected behavior, and actual behavior.
