### ISSUE TITLE
Rouge - opening chests with the shift key held down don't work correctly.

### ISSUE THREAD

**Issue by Livitan** [cannonpalms/FasterLooting#7]
Hi everyone, the addon is really useful, thanks for the work.
I encountered such a problem, I'm a rouge, when I pick chests with the shift key held down, FasterLooting still robs them automatically, a pressed key works with mobs, but there are no chests.
When disabling the addon, it works.

![alt text](https://i.imgur.com/LeSGvIW.png)

**Comment by shkabo** [comment]
I have reported same issue here https://github.com/cannonpalms/FasterLooting/issues/6 but author said it's "working as intended" and that there is no bug with it. Anyhow, due to slow reply I found similar addon that does exactly the same like this one and shift key works perfectly. 
Due to respect to the current author (@cannonpalms ) I will not post the name, but you can find it easily on curse.

**Comment by Livitan** [comment]
I have already begun to think that I am alone with this problem here.
@shkabo , thanks for the tip.

**Comment by cannonpalms** [comment]
@shkabo I'm sorry for misunderstanding your issue previously. 

I have auto-loot disabled and use shift when I want to auto-loot. When I regularly click a chest (without the auto-loot modifier held down), items are not auto-looted. 

When I tested with auto-loot enabled, I did so only on mobs, not chests. The results indicated that both scenarios (enabled w/ modifier & disabled w/o modifier) were working correctly for mobs. Additionally, as I stated above, the "disabled w/o modifier" configuration was working perfectly on chests, so I made an assumption that just as with mobs, that this extended to the other configuration.

I will test looting chests with auto-loot enabled and the modifier key held down and report back.

Thanks,
Cannon

**Comment by cannonpalms** [comment]
I believe I have discovered the cause of your issue @shkabo @Livitan .

It is not enough to briefly press the modifier key when clicking to loot. The key must be held until the loot window appears. I believe this is a limitation of the API--the earliest I am able to detect that you have begun looting something is upon the `LOOT_OPENED` event. 

Please keep the modifier held for just a brief moment longer and you will not have issues. I will search for a workaround.

Thanks,
Cannon

**Comment by cannonpalms** [comment]
- [ ] Determine if there is a way to access the modifier key state before the loot window is opened and store that value for when we process loot upon the window being ready.

**Comment by Livitan** [comment]
Yes it works, thanks. @cannonpalms
